  name: Report coverage to Codecov

  on:
    push:
      branches: 
        - pr_target_test
    pull_request_target:
      types: [labeled]
      branches: 
        - pr_target_test
  jobs:
    build-branch:
      runs-on: ubuntu-latest
      if: contains(github.event.pull_request.labels.*.name, 'safe') || github.event_name == 'push'

      name: Test coverage report
      steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: Checkout code
        if: github.event_name == 'push'
        uses: actions/checkout@v2

      - name: Checkout PR code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.8

      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Run tests
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: python run_tests.py
      - name: Upload remote controller logs on test failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: rc-logs
          path: |
            rc_stderr.log
            rc_stdout.log

      - name: Publish to Codecov 
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
