  name: Report coverage to Codecov
  
  on: [push, pull_request]
  jobs:
    build-branch:
      runs-on: ubuntu-latest

      name: Test coverage report.
      steps:
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Set up maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run : |
            pip install -r requirements-dev.txt
            pip install -r requirements-test.txt
            
      - name: Setup tmate
        uses: mxschmitt/action-tmate@v3
        
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=devopshazelcast-github
            -Dsonar.projectKey=hazelcast_hazelcast-python-client
            -Dsonar.python.coverage.reportPaths=coverage.xml
