name: Run tests
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Enter PR number to run coverage on it
        required: true
  push:
    branches:
      - Pull_request_target_integration
      - master
      - '[45].*.z'
  pull_request_target:
    branches:
      - Pull_request_target_integration
      - master
      - '[45].*.z'
    types:
      [opened, labeled]
jobs:

  test_composite_action:
    runs-on: ubuntu-latest
    name: Test composite  
    outputs:
      check-result: ${{ steps.composite.outputs.check-result }}
    steps: 
      - name: Composite
        id: composite
        uses: alisengul53/membership-check/membership@main
        with:
          organization-name: 'hazelcast'
          member-name: ${{ github.event.pull_request.head.repo.owner.login }}
          token: ${{ secrets.PAT }}
      - run: |
          echo ${{ github.event.pull_request.head.repo.owner.login }}
          echo ${{ steps.composite.outputs.check-result }}
          echo ${{ github.event_name }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'pr_builder') }}
          echo ${{ github.event.number }}
          
  run-tests:
    runs-on: ${{ matrix.os }}
    needs: [test_composite_action]
    if: contains(github.event.pull_request.labels.*.name, 'pr_builder') || github.event_name == 'push' || needs.test_composite_action.outputs.check-result == 'true' || github.event_name == 'workflow_dispatch'
    name: Run tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.10' ]
        os: [ ubuntu-latest ]
      fail-fast: false
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: Checkout code for push event
        if: github.event_name == 'push'
        uses: actions/checkout@v2

      - name: Checkout code for PR
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Checkout code for PR
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2
        
      - name: Checkout PR external
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd hazelcast-python-client
          git fetch origin pull/${{github.event.inputs.pr_number }}/head:temp_branch
          git checkout temp_branch
          
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Run tests
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: python run_tests.py
      - name: Upload remote controller logs on test failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: rc-logs-${{ matrix.python-version }}-${{ matrix.os }}
          path: |
            rc_stderr.log
            rc_stdout.log
            
      - name: Publish results to Codecov for PR
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' &&  github.event_name == 'pull_request_target' }}
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          override_pr: ${{ github.event.pull_request.number }}
          
      - name: Publish result to Codecov for PR coming from community
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          override_pr: ${{ github.event.inputs.pr_number }}
          
      - name: Publish results to Codecov for Push
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' &&  github.event_name == 'push' }}
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
